# Generated by Django 5.2.8 on 2025-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azrierl", "0002_activity_created_at_activity_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image_activity",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="activitycategory",
            name="activ_img",
            field=models.ImageField(blank=True, null=True, upload_to="activ_imgs/"),
        ),
        migrations.AddField(
            model_name="company",
            name="camp_image",
            field=models.ImageField(blank=True, null=True, upload_to="camp_img/"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="img_user/"),
        ),
    ]
